apiVersion: v1
kind: Service
metadata:
  name: metadata:
  name: {{ printf "%s-svc" .Values.appName | trunc 63 }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ .Values.appName }}