apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" .Values.appName | trunc 63 }}
  namespace: {{ .Values.appName }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
    kubernetes.io/ingres.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: {{ .Values.appURL }}
    http:
      paths:      
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ printf "%s-svc" .Values.appName | trunc 63 }}
            port:
              number: {{ .Values.service.externalPort }}
